//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookBook.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_detail
    {
        public int id { get; set; }
        public int billid { get; set; }
        public int productid { get; set; }
        public Nullable<int> discountid { get; set; }
        public int quantity { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual discount discount { get; set; }
        public virtual product product { get; set; }
    }
}
